trigger:
  - master
pr:
  - master
jobs:
  - job: Build
    strategy:
      matrix:
        # high_sierra:
        #   imageName: macos-10.13
        mojave:
          imageName: macos-10.14
    pool:
      vmImage: $(imageName)
    steps:
      - bash: |
          set -e
          if [[ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]]; then
            git fetch origin "master:master" "pull/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/head:pr"
            git checkout pr
          fi
          sudo xcode-select --switch /Applications/Xcode_10.1.app/Contents/Developer
          tap="$(brew --repo)"/Library/Taps/"$BUILD_REPOSITORY_ID"
          mkdir -p $(dirname "$tap")
          sudo ln -s "$PWD" "$tap"
          brew test-bot --bintray-org=rtimush \
                        --root-url=https://dl.bintray.com/$BUILD_REPOSITORY_ID \
                        --tap=rtimush/test-tap
          mv *.bottle.* "$ARTIFACT_STAGING_DIR/""
        env:
          IMAGE_NAME: $(imageName)
          ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: brew-test-bot.xml
          mergeTestResults: true
          buildPlatform: $(imageName)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: bottles-$(imageName)
          targetPath: $(Build.ArtifactStagingDirectory)
  - job: Publish
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: macos-10.14
    steps:
      # - task: DownloadPipelineArtifact@0
      #   inputs:
      #     artifactName: bottles-macos-10.13
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: bottles-macos-10.14
      - bash: |
          set -e
          find . -maxdepth 1 -name '*.json' -type f -print0 | xargs -0 cat
          tap="$(brew --repo)"/Library/Taps/"$BUILD_REPOSITORY_ID"
          mkdir -p $(dirname "$tap")
          sudo ln -s "$PWD" "$tap"
          brew test-bot --bintray-org=rtimush \
                        --root-url=https://dl.bintray.com/$BUILD_REPOSITORY_ID \
                        --tap=rtimush/test-tap \
                        --ci-upload
          git show
          # echo $GITHUB_DEPLOY_KEY | sed 's/\\n/\
          # /g' > github
          # chmod 0600 github
          # mkdir -p ~/.ssh
          # ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          # git remote add origin-writeable git@github.com:rtimush/homebrew-tap.git
          # GIT_SSH_COMMAND="ssh -i github" git push origin-writeable
        env:
          HOMEBREW_BINTRAY_USER: $(bintray.apiUser)
          HOMEBREW_BINTRAY_KEY: $(bintray.apiKey)
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
          # GITHUB_DEPLOY_KEY: $(github.deployKey)
